name: Build Project

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

jobs:
  build-mono:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Load from Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-ArtemisFission-WebGL
          restore-keys: |
            Library-ArtemisFission-
            Library-

      - name: Run Builder
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          # unityVersion: 2021.3.8f1

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build